Feature/#7 create authorization component
Point2Point/Chess pull request #18
Opened 2019-07-11 14:30 UTC by Krishtopchik

2019-07-11 15:07 UTC, pavelmakarets approved these changes
Sees good

2019-07-11 15:07 UTC, palexa requested changes

2019-07-11 15:07 UTC, palexa commented on src/components/Login.vue
> +    height: 200px;
Будет ли это адаптивно?

2019-07-12 07:35 UTC, Krishtopchik commented on src/components/Login.vue
> +    height: 200px;
исправил

2019-07-12 07:46 UTC, palexa approved these changes

2019-07-12 07:46 UTC, merged